from pathlib import Path
import argparse
import csv

import cv2
import numpy as np
import torch
from ultralytics import YOLO


# ============================================================
# ARGUMENTS
# ============================================================

parser = argparse.ArgumentParser()
parser.add_argument(
    "--fold",
    required=True,
    choices=["fold1", "fold2", "fold3", "fold4", "all"],
)
parser.add_argument("--imgsz", type=int, default=640)
parser.add_argument("--conf", type=float, default=0.25)
parser.add_argument("--iou", type=float, default=0.70)
parser.add_argument(
    "--project-root",
    type=Path,
    default=Path.home() / "ExoDisc_project",
    help="Project root containing experiments/yolo.",
)
parser.add_argument(
    "--results-root",
    type=Path,
    default=Path.home() / "ExoDisc_results",
    help="Root directory containing YOLO checkpoints and evaluation outputs.",
)
args = parser.parse_args()


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = args.project_root.expanduser().resolve()
RESULTS_ROOT = args.results_root.expanduser().resolve()

# Fold datasets generated by train_yolo11m_fold.py
EXP_ROOT = PROJECT_ROOT / "experiments" / "yolo" 

# Ultralytics training outputs
MODEL_ROOT = RESULTS_ROOT / "yolo11" 

# Semantic evaluation outputs
OUT_DIR = RESULTS_ROOT / "semantic_benchmark" / "yolo11m_seg"
OUT_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# CLASSES
# ============================================================

CLASS_NAMES = {
    0: "aspirator",
    1: "burr",
    2: "retractor",
    3: "spatula",
    4: "forceps",
    5: "scalpel",
    6: "curettes",
    7: "electrocautery",
    8: "disc",
    9: "dura",
    10: "ligament",
    11: "herniation",
}

NUM_FOREGROUND_CLASSES = len(CLASS_NAMES)
BACKGROUND_ID = NUM_FOREGROUND_CLASSES
NUM_EVAL_CLASSES = NUM_FOREGROUND_CLASSES + 1

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}


# ============================================================
# MASK CONVERSION
# ============================================================

def yolo_label_to_semantic_mask(label_path: Path, height: int, width: int) -> np.ndarray:
    """Convert a YOLO segmentation label file into a semantic mask.

    Foreground values are 0..11 and background is BACKGROUND_ID.
    """
    mask = np.full((height, width), BACKGROUND_ID, dtype=np.uint8)

    if not label_path.exists():
        return mask

    with open(label_path, "r", encoding="utf-8") as file:
        for line in file:
            parts = line.strip().split()
            if len(parts) < 7:
                continue

            class_id = int(float(parts[0]))
            if class_id < 0 or class_id >= NUM_FOREGROUND_CLASSES:
                continue

            coords = np.asarray(parts[1:], dtype=np.float32)
            if coords.size % 2 != 0:
                continue

            coords = coords.reshape(-1, 2)
            coords[:, 0] *= width
            coords[:, 1] *= height

            polygon = np.rint(coords).astype(np.int32)
            polygon[:, 0] = np.clip(polygon[:, 0], 0, width - 1)
            polygon[:, 1] = np.clip(polygon[:, 1], 0, height - 1)

            cv2.fillPoly(mask, [polygon], class_id)

    return mask


def prediction_to_semantic_mask(result, height: int, width: int) -> np.ndarray:
    """Merge YOLO instance predictions into one semantic mask.

    Lower-confidence masks are painted first, so higher-confidence masks win in
    overlapping areas.
    """
    pred_mask = np.full((height, width), BACKGROUND_ID, dtype=np.uint8)

    if result.masks is None or result.boxes is None:
        return pred_mask

    masks = result.masks.data
    classes = result.boxes.cls.detach().cpu().numpy().astype(np.int64)
    confidences = result.boxes.conf.detach().cpu().numpy()

    masks = torch.nn.functional.interpolate(
        masks[:, None].float(),
        size=(height, width),
        mode="nearest",
    )[:, 0]
    masks = masks.detach().cpu().numpy() > 0.5

    order = np.argsort(confidences)

    for index in order:
        class_id = int(classes[index])
        if 0 <= class_id < NUM_FOREGROUND_CLASSES:
            pred_mask[masks[index]] = class_id

    return pred_mask


# ============================================================
# METRICS
# ============================================================

def update_confusion_matrix(
    confusion: np.ndarray,
    ground_truth: np.ndarray,
    prediction: np.ndarray,
) -> None:
    valid = (
        (ground_truth >= 0)
        & (ground_truth < NUM_EVAL_CLASSES)
        & (prediction >= 0)
        & (prediction < NUM_EVAL_CLASSES)
    )

    gt = ground_truth[valid].astype(np.int64)
    pred = prediction[valid].astype(np.int64)

    indices = NUM_EVAL_CLASSES * gt + pred
    confusion += np.bincount(
        indices,
        minlength=NUM_EVAL_CLASSES ** 2,
    ).reshape(NUM_EVAL_CLASSES, NUM_EVAL_CLASSES)


def compute_metrics(confusion: np.ndarray) -> dict:
    true_positive = np.diag(confusion).astype(np.float64)
    false_positive = confusion.sum(axis=0) - true_positive
    false_negative = confusion.sum(axis=1) - true_positive

    iou_denominator = true_positive + false_positive + false_negative
    dice_denominator = 2.0 * true_positive + false_positive + false_negative
    accuracy_denominator = confusion.sum(axis=1)

    iou = np.divide(
        true_positive,
        iou_denominator,
        out=np.full(NUM_EVAL_CLASSES, np.nan, dtype=np.float64),
        where=iou_denominator > 0,
    )
    dice = np.divide(
        2.0 * true_positive,
        dice_denominator,
        out=np.full(NUM_EVAL_CLASSES, np.nan, dtype=np.float64),
        where=dice_denominator > 0,
    )
    accuracy = np.divide(
        true_positive,
        accuracy_denominator,
        out=np.full(NUM_EVAL_CLASSES, np.nan, dtype=np.float64),
        where=accuracy_denominator > 0,
    )

    foreground_iou = iou[:NUM_FOREGROUND_CLASSES]
    foreground_dice = dice[:NUM_FOREGROUND_CLASSES]
    foreground_accuracy = accuracy[:NUM_FOREGROUND_CLASSES]

    total_pixels = confusion.sum()
    pixel_accuracy = (
        float(np.trace(confusion) / total_pixels)
        if total_pixels > 0
        else np.nan
    )

    foreground_pixels = confusion[:NUM_FOREGROUND_CLASSES, :].sum()
    if foreground_pixels > 0:
        frequencies = (
            confusion[:NUM_FOREGROUND_CLASSES, :].sum(axis=1)
            / foreground_pixels
        )
        foreground_fwiou = float(np.nansum(frequencies * foreground_iou))
    else:
        foreground_fwiou = np.nan

    return {
        "mIoU": float(np.nanmean(foreground_iou)),
        "mean_Dice": float(np.nanmean(foreground_dice)),
        "pixel_accuracy_with_background": pixel_accuracy,
        "mean_accuracy": float(np.nanmean(foreground_accuracy)),
        "foreground_FWIoU": foreground_fwiou,
        "background_IoU": float(iou[BACKGROUND_ID]),
        "ious": iou,
        "dices": dice,
        "accuracies": accuracy,
    }


# ============================================================
# EVALUATION
# ============================================================

def evaluate_fold(fold: str) -> dict:
    experiment_dir = EXP_ROOT / fold
    images_dir = experiment_dir / "images" / "val"
    labels_dir = experiment_dir / "labels" / "val"
    model_path = MODEL_ROOT / fold / "weights" / "best.pt"

    if not images_dir.exists():
        raise FileNotFoundError(f"Validation images directory not found: {images_dir}")
    if not labels_dir.exists():
        raise FileNotFoundError(f"Validation labels directory not found: {labels_dir}")
    if not model_path.exists():
        raise FileNotFoundError(f"Model checkpoint not found: {model_path}")

    print(f"\n===== {fold} =====", flush=True)
    print(f"Model:  {model_path}", flush=True)
    print(f"Images: {images_dir}", flush=True)
    print(f"Labels: {labels_dir}", flush=True)

    model = YOLO(str(model_path))

    image_files = sorted(
        path
        for path in images_dir.iterdir()
        if path.suffix.lower() in IMAGE_EXTS
    )

    if not image_files:
        raise RuntimeError(f"No validation images found in: {images_dir}")

    confusion = np.zeros(
        (NUM_EVAL_CLASSES, NUM_EVAL_CLASSES),
        dtype=np.int64,
    )

    missing_labels = 0

    for index, image_path in enumerate(image_files, start=1):
        image = cv2.imread(str(image_path))
        if image is None:
            print(f"WARNING: unreadable image: {image_path}", flush=True)
            continue

        height, width = image.shape[:2]
        label_path = labels_dir / f"{image_path.stem}.txt"
        if not label_path.exists():
            missing_labels += 1

        ground_truth = yolo_label_to_semantic_mask(
            label_path,
            height,
            width,
        )

        result = model.predict(
            source=str(image_path),
            imgsz=args.imgsz,
            conf=args.conf,
            iou=args.iou,
            verbose=False,
        )[0]

        prediction = prediction_to_semantic_mask(
            result,
            height,
            width,
        )

        update_confusion_matrix(confusion, ground_truth, prediction)

        if index % 100 == 0 or index == len(image_files):
            print(
                f"{fold}: {index}/{len(image_files)} images evaluated",
                flush=True,
            )

    metrics = compute_metrics(confusion)

    fold_metrics_path = OUT_DIR / f"{fold}_metrics.csv"
    fold_class_path = OUT_DIR / f"{fold}_per_class.csv"
    confusion_path = OUT_DIR / f"{fold}_confusion_matrix.csv"

    metric_columns = [
        "fold",
        "mIoU",
        "mean_Dice",
        "pixel_accuracy_with_background",
        "mean_accuracy",
        "foreground_FWIoU",
        "background_IoU",
        "n_images",
        "missing_labels",
    ]

    with open(fold_metrics_path, "w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=metric_columns)
        writer.writeheader()
        writer.writerow({
            "fold": fold,
            "mIoU": metrics["mIoU"],
            "mean_Dice": metrics["mean_Dice"],
            "pixel_accuracy_with_background": metrics["pixel_accuracy_with_background"],
            "mean_accuracy": metrics["mean_accuracy"],
            "foreground_FWIoU": metrics["foreground_FWIoU"],
            "background_IoU": metrics["background_IoU"],
            "n_images": len(image_files),
            "missing_labels": missing_labels,
        })

    with open(fold_class_path, "w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow([
            "fold",
            "class_id",
            "class_name",
            "IoU",
            "Dice",
            "Accuracy",
        ])

        for class_id in range(NUM_FOREGROUND_CLASSES):
            writer.writerow([
                fold,
                class_id,
                CLASS_NAMES[class_id],
                metrics["ious"][class_id],
                metrics["dices"][class_id],
                metrics["accuracies"][class_id],
            ])

    np.savetxt(
        confusion_path,
        confusion,
        delimiter=",",
        fmt="%d",
    )

    print(f"{fold} mIoU = {metrics['mIoU']:.4f}", flush=True)
    print(f"{fold} Dice = {metrics['mean_Dice']:.4f}", flush=True)
    print(f"Saved in: {OUT_DIR}", flush=True)

    return {
        "fold": fold,
        "mIoU": metrics["mIoU"],
        "mean_Dice": metrics["mean_Dice"],
        "pixel_accuracy_with_background": metrics["pixel_accuracy_with_background"],
        "mean_accuracy": metrics["mean_accuracy"],
        "foreground_FWIoU": metrics["foreground_FWIoU"],
        "background_IoU": metrics["background_IoU"],
    }


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    print(f"PROJECT_ROOT: {PROJECT_ROOT}", flush=True)
    print(f"RESULTS_ROOT: {RESULTS_ROOT}", flush=True)
    print(f"EXPERIMENT_ROOT: {EXP_ROOT}", flush=True)
    print(f"MODEL_ROOT: {MODEL_ROOT}", flush=True)
    print(f"OUTPUT_ROOT: {OUT_DIR}", flush=True)

    folds = (
        ["fold1", "fold2", "fold3", "fold4"]
        if args.fold == "all"
        else [args.fold]
    )

    all_rows = [evaluate_fold(fold) for fold in folds]

    if len(all_rows) > 1:
        summary_path = OUT_DIR / "summary_folds.csv"
        mean_std_path = OUT_DIR / "summary_mean_std.csv"

        with open(summary_path, "w", newline="", encoding="utf-8") as file:
            writer = csv.DictWriter(file, fieldnames=all_rows[0].keys())
            writer.writeheader()
            writer.writerows(all_rows)

        metric_names = [
            "mIoU",
            "mean_Dice",
            "pixel_accuracy_with_background",
            "mean_accuracy",
            "foreground_FWIoU",
            "background_IoU",
        ]

        with open(mean_std_path, "w", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerow(["metric", "mean", "std"])

            for metric_name in metric_names:
                values = np.asarray(
                    [row[metric_name] for row in all_rows],
                    dtype=np.float64,
                )
                writer.writerow([
                    metric_name,
                    np.nanmean(values),
                    np.nanstd(values, ddof=1),
                ])

        print("\n===== SUMMARY =====", flush=True)
        for metric_name in metric_names:
            values = np.asarray(
                [row[metric_name] for row in all_rows],
                dtype=np.float64,
            )
            print(
                f"{metric_name}: "
                f"{np.nanmean(values):.4f} +/- "
                f"{np.nanstd(values, ddof=1):.4f}",
                flush=True,
            )

        print(f"\nSaved: {summary_path}", flush=True)
        print(f"Saved: {mean_std_path}", flush=True)


if __name__ == "__main__":
    main()
